import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/header/side-nav";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/footer/footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}>
        <div className="flex flex-col min-h-screen">
          <div className="flex flex-1">
            <Sidebar />
            <div className="flex-1 flex flex-col">
              <main className="flex-1 p-4 mt-[80px] pb-20"> {/* Increased bottom padding */}
                {children}
              </main>
            </div>
          </div>
          <Footer/> {/* Ensure footer stays at bottom */}
        </div>
        <ToastContainer />
      </body>
    </html>
  );
}
