import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/Components/header/side-nav";
import { ToastContainer } from "react-toastify";
import Footer from "@/Components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex relative">
          <Sidebar /> {/* Sidebar on the left */}
          <Footer/>
          <ToastContainer />
          <main className="flex-1 p-4 transition-all duration-300 ml-[0px] md:ml-[0px] mr-[0px] mt-[80px] mb-[-100px]">
            {/* Add margin-top to offset header */}
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}